### ISSUE TITLE
视频的打开websocket链接是做在视频控件上

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo-vue#4]
有客户报数据不对，贝乐坊杂物间监控，该视频没有打开，但是在线用户是1，也就是说，还是要在页面监听视频控件的启动、停止事件

**Comment by veraGe** [comment]
视频播放后才进行websocket连接，获取视频的播放状态
src/pages/video/schoolVideoDetails.vue
